;              
CREATE USER IF NOT EXISTS SA SALT '3f09ef34b87264d9' HASH 'c5db8a468f7c96fc41ab3cc2a16369c6e1f2bbac806562ab1a4c3b843c7fecc2' ADMIN;            
CREATE CACHED TABLE PUBLIC.TOKEN(
    TOKENKEY UUID NOT NULL,
    CREATED TIMESTAMP,
    ROLESJSON VARCHAR(255),
    USERNAME VARCHAR(255),
    VALIDUNTIL TIMESTAMP
);        
ALTER TABLE PUBLIC.TOKEN ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(TOKENKEY);             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TOKEN;    
CREATE CACHED TABLE PUBLIC.USER(
    AUTH VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    ACCESSED TIMESTAMP,
    CREATED TIMESTAMP,
    MAIL VARCHAR(255),
    MODIFIED TIMESTAMP,
    NAME VARCHAR(255),
    ORGANIZATION VARCHAR(255),
    TERMSACCEPTED TIMESTAMP,
    TERMSVERSION INTEGER NOT NULL,
    VERSION BIGINT NOT NULL
);        
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(AUTH, USERNAME);        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER;     
