ALTER TABLE user_table ALTER COLUMN accessed TYPE TIMESTAMP(6) WITH TIME ZONE USING accessed AT TIME ZONE 'UTC';
ALTER TABLE user_table ALTER COLUMN created TYPE TIMESTAMP(6) WITH TIME ZONE USING created AT TIME ZONE 'UTC';
ALTER TABLE user_table ALTER COLUMN modified TYPE TIMESTAMP(6) WITH TIME ZONE USING modified AT TIME ZONE 'UTC';
ALTER TABLE user_table ALTER COLUMN termsaccepted TYPE TIMESTAMP(6) WITH TIME ZONE USING termsaccepted AT TIME ZONE 'UTC';

DROP TABLE "token";