ALTER TABLE jobhistory ALTER COLUMN endtime TYPE TIMESTAMP(6) WITH TIME ZONE USING endtime AT TIME ZONE 'UTC';
ALTER TABLE jobhistory ALTER COLUMN starttime TYPE TIMESTAMP(6) WITH TIME ZONE USING starttime AT TIME ZONE 'UTC';
ALTER TABLE jobhistory ALTER COLUMN created TYPE TIMESTAMP(6) WITH TIME ZONE USING created AT TIME ZONE 'UTC';
