package fi.csc.chipster.sessiondb.model;

import java.io.Serializable;
import java.util.UUID;

import jakarta.persistence.Column;

public class DatasetIdPair implements Serializable {

	@Column(columnDefinition = "uuid", updatable = false) // uuid instead of binary
	private UUID sessionId;
	@Column(columnDefinition = "uuid", updatable = false) // uuid instead of binary
	private UUID datasetId;

	public DatasetIdPair() {
		// needed by JSON (de)serialization
	}

	public DatasetIdPair(UUID sessionId, UUID jobId) {
		this.sessionId = sessionId;
		this.datasetId = jobId;
	}

	public UUID getSessionId() {
		return sessionId;
	}

	public UUID getDatasetId() {
		return datasetId;
	}

	/*
	 * generated by Eclipse
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((datasetId == null) ? 0 : datasetId.hashCode());
		result = prime * result + ((sessionId == null) ? 0 : sessionId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DatasetIdPair other = (DatasetIdPair) obj;
		if (datasetId == null) {
			if (other.datasetId != null)
				return false;
		} else if (!datasetId.equals(other.datasetId))
			return false;
		if (sessionId == null) {
			if (other.sessionId != null)
				return false;
		} else if (!sessionId.equals(other.sessionId))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return datasetId.toString().substring(0, 4);
	}
}