package fi.csc.chipster.sessiondb.model;

import java.io.Serializable;
import java.util.UUID;

import javax.persistence.Column;

public class WorkflowPlanIdPair implements Serializable {

	@Column( columnDefinition = "uuid", updatable = false ) // uuid instead of binary
	private UUID sessionId;
	@Column( columnDefinition = "uuid", updatable = false ) // uuid instead of binary
	private UUID workflowPlanId;
	
	public WorkflowPlanIdPair() {
		// needed by JSON (de)serialization
	}

	public WorkflowPlanIdPair(UUID sessionId, UUID workflowPlanId) {
		this.sessionId = sessionId;
		this.workflowPlanId = workflowPlanId;
	}

	public UUID getSessionId() {
		return sessionId;
	}

	public UUID getWorkflowPlanId() {
		return workflowPlanId;
	}

	/* 
	 * generated by Eclipse
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((workflowPlanId == null) ? 0 : workflowPlanId.hashCode());
		result = prime * result + ((sessionId == null) ? 0 : sessionId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		WorkflowPlanIdPair other = (WorkflowPlanIdPair) obj;
		if (workflowPlanId == null) {
			if (other.workflowPlanId != null)
				return false;
		} else if (!workflowPlanId.equals(other.workflowPlanId))
			return false;
		if (sessionId == null) {
			if (other.sessionId != null)
				return false;
		} else if (!sessionId.equals(other.sessionId))
			return false;
		return true;
	}
	
	@Override
	public String toString() {
		return workflowPlanId.toString().substring(0, 4);
	}
}