apiVersion: v1
kind: Pod
metadata:
  name: ""
  labels:
    comp-job: ""
spec:
  containers:
  - name: comp-job
    image: ""
    imagePullPolicy: Always
    command: ["java",  "-cp", "lib/*:", "fi.csc.chipster.comp.SingleShotComp"]
    resources:
      limits:
        cpu: ""
        memory: ""
      requests:
        cpu: ""
        memory: ""
    volumeMounts:
    - mountPath: /opt/chipster/conf
      name: conf
      readOnly: true
    - mountPath: /opt/chipster/tools
      name: tools-bin
      readOnly: true
    - mountPath: /opt/chipster/jobs-data
      name: jobs-data
  volumes:
  - name: conf
    secret:
      defaultMode: 420
      secretName: single-shot-comp
  - name: tools-bin
    persistentVolumeClaim:
      claimName: tools-bin-chipster-3.16.6
  - emptyDir: {}
    name: jobs-data  
  restartPolicy: Never