apiVersion: v1
kind: Pod
metadata:
  name: ""
  labels:
    comp-job: ""
    comp-job-anti-affinity: True
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: comp-job-anti-affinity
              operator: In
              values:
              - True
          topologyKey: "kubernetes.io/hostname"
  containers:
  - name: comp-job
    image: ""
    imagePullPolicy: ""
    command: ["java",  "-cp", "lib/*:", "fi.csc.chipster.comp.SingleShotComp"]
    volumeMounts:
    - mountPath: /opt/chipster/conf
      name: conf
      readOnly: true
    - mountPath: /opt/chipster/jobs-data
      name: jobs-data
  volumes:
  - name: conf
    secret:
      defaultMode: 420
      secretName: single-shot-comp
  restartPolicy: Never