ALTER TABLE dataset ALTER COLUMN created TYPE TIMESTAMP(6) WITH TIME ZONE USING created AT TIME ZONE 'UTC';

ALTER TABLE file ALTER COLUMN filecreated TYPE TIMESTAMP(6) WITH TIME ZONE USING filecreated AT TIME ZONE 'UTC';

ALTER TABLE job ALTER COLUMN created TYPE TIMESTAMP(6) WITH TIME ZONE USING created AT TIME ZONE 'UTC';

ALTER TABLE job ALTER COLUMN endtime TYPE TIMESTAMP(6) WITH TIME ZONE USING endtime AT TIME ZONE 'UTC';

ALTER TABLE job ALTER COLUMN starttime TYPE TIMESTAMP(6) WITH TIME ZONE USING starttime AT TIME ZONE 'UTC';

ALTER TABLE news ALTER COLUMN created TYPE TIMESTAMP(6) WITH TIME ZONE USING created AT TIME ZONE 'UTC';

ALTER TABLE news ALTER COLUMN modified TYPE TIMESTAMP(6) WITH TIME ZONE USING modified AT TIME ZONE 'UTC';

ALTER TABLE rule ALTER COLUMN created TYPE TIMESTAMP(6) WITH TIME ZONE USING created AT TIME ZONE 'UTC';

ALTER TABLE session ALTER COLUMN accessed TYPE TIMESTAMP(6) WITH TIME ZONE USING accessed AT TIME ZONE 'UTC';

ALTER TABLE session ALTER COLUMN created TYPE TIMESTAMP(6) WITH TIME ZONE USING created AT TIME ZONE 'UTC';

DROP TABLE "datasettoken";