;              
CREATE USER IF NOT EXISTS SA SALT '4b535ec5a6031408' HASH '6440d278f69554dec66aeb0acb7f1b35df2d28d028096fdd31ce69c082e15cb8' ADMIN;            
CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE START WITH 1;        
CREATE CACHED TABLE PUBLIC.DATASET(
    DATASETID UUID NOT NULL,
    CREATED TIMESTAMP,
    NAME VARCHAR(255),
    NOTES CLOB,
    SOURCEJOB BINARY,
    TYPETAGS BINARY(255),
    X INTEGER,
    Y INTEGER,
    FILEID UUID,
    SESSIONID UUID
);            
ALTER TABLE PUBLIC.DATASET ADD CONSTRAINT PUBLIC.CONSTRAINT_8 PRIMARY KEY(DATASETID);          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DATASET;  
CREATE CACHED TABLE PUBLIC.DATASETTOKEN(
    TOKENKEY UUID NOT NULL,
    USERNAME VARCHAR(255),
    VALID TIMESTAMP,
    DATASET_DATASETID UUID,
    SESSION_SESSIONID UUID
); 
ALTER TABLE PUBLIC.DATASETTOKEN ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(TOKENKEY);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DATASETTOKEN;             
CREATE CACHED TABLE PUBLIC.FILE(
    FILEID UUID NOT NULL,
    CHECKSUM VARCHAR(255),
    FILECREATED TIMESTAMP,
    SIZE BIGINT NOT NULL
);   
ALTER TABLE PUBLIC.FILE ADD CONSTRAINT PUBLIC.CONSTRAINT_20 PRIMARY KEY(FILEID);               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.FILE;     
CREATE CACHED TABLE PUBLIC.INPUT(
    DBID INTEGER NOT NULL,
    DATASETID VARCHAR(255),
    DESCRIPTION CLOB,
    DISPLAYNAME VARCHAR(255),
    INPUTID VARCHAR(255),
    TYPE VARCHAR(255),
    JOBID UUID
);
ALTER TABLE PUBLIC.INPUT ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(DBID); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.INPUT;    
CREATE CACHED TABLE PUBLIC.JOB(
    JOBID UUID NOT NULL,
    CREATED TIMESTAMP,
    CREATEDBY VARCHAR(255),
    ENDTIME TIMESTAMP,
    MODULE VARCHAR(255),
    SCREENOUTPUT CLOB,
    SOURCECODE CLOB,
    STARTTIME TIMESTAMP,
    STATE INTEGER,
    STATEDETAIL CLOB,
    TOOLCATEGORY VARCHAR(255),
    TOOLDESCRIPTION CLOB,
    TOOLID VARCHAR(255),
    TOOLNAME VARCHAR(255),
    SESSIONID UUID
);   
ALTER TABLE PUBLIC.JOB ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(JOBID);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.JOB;      
CREATE CACHED TABLE PUBLIC.METADATAENTRY(
    METADATAENTRYID BIGINT NOT NULL,
    COLUMN VARCHAR(255),
    KEY VARCHAR(255),
    VALUE VARCHAR(255),
    DATASETID UUID
);    
ALTER TABLE PUBLIC.METADATAENTRY ADD CONSTRAINT PUBLIC.CONSTRAINT_42 PRIMARY KEY(METADATAENTRYID);             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.METADATAENTRY;            
CREATE CACHED TABLE PUBLIC.PARAMETER(
    DBID INTEGER NOT NULL,
    DESCRIPTION CLOB,
    DISPLAYNAME VARCHAR(255),
    PARAMETERID VARCHAR(255),
    TYPE INTEGER,
    VALUE VARCHAR(255),
    JOBID UUID
); 
ALTER TABLE PUBLIC.PARAMETER ADD CONSTRAINT PUBLIC.CONSTRAINT_1A PRIMARY KEY(DBID);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PARAMETER;
CREATE CACHED TABLE PUBLIC.RULE(
    RULEID UUID NOT NULL,
    READWRITE BOOLEAN NOT NULL,
    SHAREDBY VARCHAR(255),
    USERNAME VARCHAR(255),
    SESSIONID UUID
);         
ALTER TABLE PUBLIC.RULE ADD CONSTRAINT PUBLIC.CONSTRAINT_26 PRIMARY KEY(RULEID);               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RULE;     
CREATE CACHED TABLE PUBLIC.SESSION(
    SESSIONID UUID NOT NULL,
    ACCESSED TIMESTAMP,
    CREATED TIMESTAMP,
    NAME VARCHAR(255),
    NOTES CLOB
);       
ALTER TABLE PUBLIC.SESSION ADD CONSTRAINT PUBLIC.CONSTRAINT_A PRIMARY KEY(SESSIONID);          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SESSION;  
ALTER TABLE PUBLIC.JOB ADD CONSTRAINT PUBLIC.FKQCCY38ODNLOKLRR9M2YXP3ML6 FOREIGN KEY(SESSIONID) REFERENCES PUBLIC.SESSION(SESSIONID) NOCHECK;  
ALTER TABLE PUBLIC.INPUT ADD CONSTRAINT PUBLIC.FKMJCP59L69PP8T781CRKL9EVSG FOREIGN KEY(JOBID) REFERENCES PUBLIC.JOB(JOBID) NOCHECK;            
ALTER TABLE PUBLIC.DATASETTOKEN ADD CONSTRAINT PUBLIC.FK2LD1310DOY7L3B9T7YP71NI37 FOREIGN KEY(SESSION_SESSIONID) REFERENCES PUBLIC.SESSION(SESSIONID) NOCHECK; 
ALTER TABLE PUBLIC.RULE ADD CONSTRAINT PUBLIC.FKMF1C6T4LD9ISRGIVJDDORTPER FOREIGN KEY(SESSIONID) REFERENCES PUBLIC.SESSION(SESSIONID) NOCHECK; 
ALTER TABLE PUBLIC.DATASET ADD CONSTRAINT PUBLIC.FKB2F4QW305W2TB5QKUDARJTEN8 FOREIGN KEY(SESSIONID) REFERENCES PUBLIC.SESSION(SESSIONID) NOCHECK;              
ALTER TABLE PUBLIC.DATASETTOKEN ADD CONSTRAINT PUBLIC.FK5D6ETF9Q0FP7ULSW2QFVAUSEX FOREIGN KEY(DATASET_DATASETID) REFERENCES PUBLIC.DATASET(DATASETID) NOCHECK; 
ALTER TABLE PUBLIC.METADATAENTRY ADD CONSTRAINT PUBLIC.FK2FTJ0A3NV8AULU6JWAAYFYDUY FOREIGN KEY(DATASETID) REFERENCES PUBLIC.DATASET(DATASETID) NOCHECK;        
ALTER TABLE PUBLIC.PARAMETER ADD CONSTRAINT PUBLIC.FKMC1HW2VKOHJOBI8GBGO383NEG FOREIGN KEY(JOBID) REFERENCES PUBLIC.JOB(JOBID) NOCHECK;        
ALTER TABLE PUBLIC.DATASET ADD CONSTRAINT PUBLIC.FKTNWJERV439JR4LMC37UVDP6HA FOREIGN KEY(FILEID) REFERENCES PUBLIC.FILE(FILEID) NOCHECK;       
